[tool.pytest.ini_options]

[tool.mypy]
exclude = [
    '^(?:([^/]+/)+(?:test_.*.py|.*_test.py))$',
    '.git',
    '.github',
    '.mypy_cache',
    '__pycache__',
    '.pytest_cache',
    'venv'
]
ignore_errors = 'False'

[tool.black]
line-length = 120
extend-exclude = """
/
^(?:(?:[^/]+/)+(?:test_.*\\.py|.*_test\\.py))$
| .github
/
"""
