name: CI

on: [push, workflow_dispatch]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: ./.github/run.sh --no-lint
      - name: Lint
        run: ./.github/run.sh --no-test
